### ISSUE TITLE
Error!

### ISSUE THREAD

**Issue by torianBr** [stephenlb/spoken#1]
const recognition = new webkitSpeechRecognition();
                                  ^

ReferenceError: webkitSpeechRecognition is not defined

**Comment by torianBr** [comment]
Are you using `speechkitt` ?

**Comment by stephenlb** [comment]
Hi!  Which browser are you running?  Currently this is only supported in Google Chrome browsers.

**Comment by stephenlb** [comment]
Push update.  The speechRecognition is no longer required in the browser and you can use `spoken.say` now in Firefox, Edge, Opera and of course Chrome.

**Comment by torianBr** [comment]
Yeah, I expected to use with terminal. Thank's!
