### ISSUE TITLE
import spoken from 'spoken' dont work

### ISSUE THREAD

**Issue by LuizLeite** [stephenlb/spoken#2]
Hi.

How to use with: "import spoken from 'spoken'?

Can you given a example with Webpack?

Tanks.

**Comment by stephenlb** [comment]
Checking into this.

**Comment by stephenlb** [comment]
Making updates and will post them!

**Comment by stephenlb** [comment]
Almost done...

**Comment by stephenlb** [comment]
Added support for modules.

```html
<script type="module">
import spoken from './node_modules/spoken/build/spoken.js';
spoken.say('Should I turn the hallway light on?').then( speech => {
    spoken.listen().then( transcript =>
        console.log("Answer: " + transcript) )
} )
</script>
```

**Comment by LuizLeite** [comment]
Tanks.
I will try it.
Luiz Leite
 

    Em sexta-feira, 3 de agosto de 2018 18:20:54 BRT, Stephen L. Blum <notifications@github.com> escreveu:  
 
 
Added support for modules.
<script type="module">
import spoken from './node_modules/spoken/build/spoken.js';
spoken.say('Should I turn the hallway light on?').then( speech => {
    spoken.listen().then( transcript =>
        console.log("Answer: " + transcript) )
} )
</script>

**Comment by stephenlb** [comment]
Sweet!

**Comment by LuizLeite** [comment]
Hi.
More one question.
How to choose a voice to speek?
There are two pt-BR in list of voices.
Tank you again.
Luiz Leite
 

    Em sexta-feira, 3 de agosto de 2018 19:26:03 BRT, Stephen L. Blum <notifications@github.com> escreveu:  
 
 
Sweet!

**Comment by stephenlb** [comment]
By default 'pt-BR' was selected automatically for you `spoken.recognition.language = navigator.language;`.
You can get a list of voices using the following example:

```javascript
// Set native voice language
spoken.recognition.language = 'en-US';

// Get a List of Voices with promise callback
spoken.voices().then( voices => console.log(voices) );
```

Here is a full example:

```javascript
(async function() {
    // List of English Speaking Voices
    spoken.recognition.language = navigator.language || 'en-US';
    let voices = (await spoken.voices()).filter( v => !v.lang.indexOf('en') );
    
    // Use the First Voice
    spoken.say( 'Welcome to flavor town.', voices[0] );
})()
```
