### ISSUE TITLE
Voices && Spoken.say

### ISSUE THREAD

**Issue by hwanderlust** [stephenlb/spoken#4]
I believe only the standard English voice works now. 

The others, even in your test demo repo, doesn't work anymore. 

Therefore it won't work for other languages/voices either. 

Not sure if it's an update to the Web Speech API or the Chrome browser.

**Comment by stephenlb** [comment]
Thank you for reporting this, will review and provide a fix.

**Comment by stephenlb** [comment]
I'm not getting any errors.  This is is working for me right now.

**Comment by stephenlb** [comment]
These all work as expected:

```javascript
spoken.say( 'Welcome to flavor town.', 'Alex' )
spoken.say( 'Welcome to flavor town.', 'Google Deutsch' )
spoken.say( 'Welcome to flavor town.', 'Veena' )
```

**Comment by hwanderlust** [comment]
Ooh they changed the names! NVM, sorry

**Comment by stephenlb** [comment]
🎉 happy it is working for you 🎉  hope you have a great day! ❤️
