### ISSUE TITLE
React Native

### ISSUE THREAD

**Issue by phillipnunes** [stephenlb/spoken#5]
Hi,

Do you know if it works with React Native? I built a simple app and imported your lib with `spoken.say('Hello there!');`, but when I run in the android smartphone, it is not returning sound or any errors.

Thanks,
Phillip.

**Comment by stephenlb** [comment]
This may work in Cordova/PhoneGap and is _unlikely_ to work with ReactNative. ReactNative builds native-views rather than web-views.

**Comment by stephenlb** [comment]
You may be able to add a hidden webview in your reactnative app which should make this work.

**Comment by stephenlb** [comment]
https://facebook.github.io/react-native/docs/webview - webview for react native

**Comment by phillipnunes** [comment]
Ok, I will take a look.

Thanks!
